In [1]:
from __future__ import print_function
import torch

# Different initialization methods for tensors

In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[1.9284e+31, 3.2314e-18, 6.5987e-07],
        [2.5788e-09, 6.3006e-10, 1.0871e-05],
        [5.2671e-08, 8.4646e-07, 2.7597e-06],
        [8.3902e-07, 2.4178e-18, 2.6302e+20],
        [6.1949e-04, 1.0256e-08, 2.5783e-09]])


In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7500, 0.1905, 0.6655],
        [0.7723, 0.0047, 0.9472],
        [0.1233, 0.9770, 0.3221],
        [0.4774, 0.4424, 0.9220],
        [0.4394, 0.6153, 0.8627]])


In [8]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([0.5, 0.55])
print(x)

tensor([0.5000, 0.5500])


## Create tensor based on tensor
You can override params, like from double to float, size will match

In [11]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 0.9813,  1.3686,  0.2253],
        [-2.2879, -1.7084, -0.6459],
        [-1.9560, -0.4186, -1.4445],
        [-0.2139,  1.8385,  0.1303],
        [ 0.0458, -0.5976, -0.0768]])


In [14]:
print(x.size()) # this is a tuple supporting tuple operations

torch.Size([5, 3])


# Operations

In [16]:
y = torch.rand(5,3) # ceates 5 rows, 3 columns with random values
print(y)
print(x+y) # values of x and y added up

tensor([[0.0010, 0.4292, 0.7214],
        [0.9278, 0.2184, 0.4676],
        [0.9819, 0.3264, 0.7127],
        [0.8208, 0.9801, 0.2135],
        [0.8391, 0.6467, 0.0128]])
tensor([[ 0.9823,  1.7978,  0.9467],
        [-1.3601, -1.4900, -0.1783],
        [-0.9740, -0.0923, -0.7318],
        [ 0.6069,  2.8186,  0.3439],
        [ 0.8849,  0.0491, -0.0639]])


In [17]:
print(torch.add(x,y)) # should yield the same result

tensor([[ 0.9823,  1.7978,  0.9467],
        [-1.3601, -1.4900, -0.1783],
        [-0.9740, -0.0923, -0.7318],
        [ 0.6069,  2.8186,  0.3439],
        [ 0.8849,  0.0491, -0.0639]])


## Providing output tensor

In [20]:
result = torch.empty(5,3) #
x = torch.rand(5,3)
y = torch.rand(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[1.1161, 1.1123, 1.0947],
        [1.0978, 0.6209, 1.4541],
        [1.5137, 1.5147, 0.7905],
        [0.4728, 0.5148, 0.8523],
        [1.1155, 0.7982, 0.2832]])


In [24]:
print(x)
print(y)
y.add_(x) # in place addition
print(y)
# Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

tensor([[0.7251, 0.6058, 0.6864],
        [0.8911, 0.1436, 0.8933],
        [0.5411, 0.8508, 0.2530],
        [0.4506, 0.1460, 0.1152],
        [0.4661, 0.1639, 0.0145]])
tensor([[1.1161, 1.1123, 1.0947],
        [1.0978, 0.6209, 1.4541],
        [1.5137, 1.5147, 0.7905],
        [0.4728, 0.5148, 0.8523],
        [1.1155, 0.7982, 0.2832]])
tensor([[1.8411, 1.7181, 1.7811],
        [1.9889, 0.7645, 2.3474],
        [2.0548, 2.3655, 1.0434],
        [0.9234, 0.6608, 0.9675],
        [1.5816, 0.9621, 0.2977]])


In [26]:
print(x[:, 1]) # all rows in column index: 1

tensor([0.6058, 0.1436, 0.8508, 0.1460, 0.1639])


## Resize tensor

In [28]:
x = torch.randn(4, 4)
print(x)

tensor([[ 0.7155,  1.0878,  0.6631, -0.6212],
        [ 1.1535, -1.0651, -1.0404,  0.4767],
        [-0.7174,  0.9253,  0.2814, -1.9207],
        [-0.0461,  1.3341,  0.2049, -0.6543]])


In [30]:
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred/deduced from other dimensions

print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 0.7155,  1.0878,  0.6631, -0.6212],
        [ 1.1535, -1.0651, -1.0404,  0.4767],
        [-0.7174,  0.9253,  0.2814, -1.9207],
        [-0.0461,  1.3341,  0.2049, -0.6543]])
tensor([ 0.7155,  1.0878,  0.6631, -0.6212,  1.1535, -1.0651, -1.0404,  0.4767,
        -0.7174,  0.9253,  0.2814, -1.9207, -0.0461,  1.3341,  0.2049, -0.6543])
tensor([[ 0.7155,  1.0878,  0.6631, -0.6212,  1.1535, -1.0651, -1.0404,  0.4767],
        [-0.7174,  0.9253,  0.2814, -1.9207, -0.0461,  1.3341,  0.2049, -0.6543]])


In [31]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7410])
0.7409797310829163


## NumPy array conversion

In [32]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [35]:
b = a.numpy()
print(b)
b+1 # for funs

[1. 1. 1. 1. 1.]


array([2., 2., 2., 2., 2.], dtype=float32)

In [36]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Convert NumPy Array to Torch Tensor

In [37]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors
Tensors can be moved onto any device using the ```.to``` method.

Let us run this cell only if CUDA is available.
We will use ``torch.device`` objects to move tensors in and out of GPU

In [40]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
torch.cuda.is_available()

False